# Generated by Django 6.0.6 on 2026-06-17 08:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_remove_complaint_officer_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='investigation_report',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='reports/'),
        ),
    ]
