# Generated by Django 6.0.6 on 2026-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(max_length=100)),
                ('article_url', models.URLField(max_length=1000, unique=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cyber News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('published_date', models.DateTimeField()),
                ('reference_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('result', models.CharField(choices=[('SAFE', 'SAFE'), ('SUSPICIOUS', 'SUSPICIOUS'), ('PHISHING', 'PHISHING')], default='SAFE', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
